# Custom biosynthesis modules for amino acids and B vitamins
### For use with the anvi'o program anvi-estimate-metabolism

This repository provides access to the custom metabolic modules generated by Armando Pacheco-Valenciana et al. in "Microbial model communities reveal widespread auxotrophies in abundant bacteria" ([link to _biorxiv_ preprint](https://doi.org/10.1101/2025.04.28.650956)).

It includes 30 custom modules that each consolidates multiple [KEGG modules](https://www.kegg.jp/kegg/module.html) for the biosynthesis of one amino acid or B vitamin. In the cases where the KEGG Module database does not contain any biosynthesis modules for a given compound (such as Alanine and Aspartate), we provide a new module that is not based on any existing KEGG module. The only exception to the 'one compound - one module' rule is vitamin B12, for which we have described the aerobic and anaerobic biosynthesis pathways in separate modules (`B12_00` and `B12_01`, respectively).

The data is designed for use with [anvi'o](https://anvio.org/) (version `v8` or `v8-dev`), and specifically the programs [`anvi-setup-user-modules`](https://anvio.org/help/8/programs/anvi-setup-user-modules/) and [`anvi-estimate-metabolism`](https://anvio.org/help/8/programs/anvi-estimate-metabolism/).

The table below shows the custom modules we created. There are twenty-one amino acid biosynthesis modules (for the standard twenty proteinogenic amino acids, plus the important precursor Chorismate), and nine B vitamin modules (including two for B12).

|**Amino Acid/Vitamin**|**Precursor**|**Module Combinations**|**3-letter Code**|**Custom Module ID**|
|:--|:--|:--|:--|:--|
|Alanine|Pyruvate|Entirely novel module|ALA|ALA_00|
|Aspartate|Pyruvate|Entirely novel module|ASP|ASP_00|
|Asparagine|Aspartate|Entirely novel module|ASN|ASN_00|
|Valine|Pyruvate|M00019|VAL|VAL_00|
|Leucine|Pyruvate|M00019 (Valine) M00432|LEU|LEU_00|
|Methionine|Aspartate|M00017|MET|MET_00|
|Threonine|Aspartate|M00018|THR|THR_00|
|Isoleucine|Pyruvate OR Threonine|combo of M00570 and M00535|ILE|ILE_00|
|Lysine|Aspartate|combo of 4 modules for Lys|LYS|LYS_00|
|Serine|3-phosphoglycerate|M00020|SER|SER_00|
|Cysteine|Serine|M00021 or M00338|CYS|CYS_00|
|Glycine|Serine|Entirely novel module|GLY|GLY_00|
|Glutamate|2-oxoglutarate|Entirely novel module|GLU|GLU_00|
|Glutamine|Glutamate|Entirely novel module|GLN|GLN_00|
|Arginine|Glutamate|combo of M00845 and M00844 with one step from M00028|ARG|ARG_00|
|Proline|Glutamate|M00015 or ((M00028 or M00763) and reaction for ornithine => proline)|PRO|PRO_00|
|Chorismate (precursor for Trp,Phe,Tyr)|Erythrose-4P|M00022|CHO|CHO_00|
|Tryptophan|Chorismate|M00023|TRP|TRP_00|
|Phenylalanine|Chorismate|M00024 or M00910|PHE|PHE_00|
|Tyrosine|Chorismate|M00025 or M00040|TYR|TYR_00|
|Histidine|PRPP|M00026|HIS|HIS_00|
|Thiamine (B1)|AIR|combo of M00127 and M00895|B01|B01_00|
|Riboflavin (B2)|GTP|M00125|B02|B02_00|
|Niacin/NAD (B3)|Aspartate OR Tryptophan|combo of M00115 and M00912|B03|B03_00|
|Pantothenic Acid (B5)|valine AND (aspartate OR Spermine)|combo of M00119 and M00913|B05|B05_00|
|Pyroxidine (B6)|Erythrose-4P or R5P|M00124 or M00916|B06|B06_00|
|Biotin (B7)|Pimeloyl-ACP OR similar compounds|combo of M00123 and M00950|B07|B07_00|
|Folic Acid (B9)|GTP|combo of M001216, M00840, M00841|B09|B09_00|
|Cobalamin (B12) - aerobic|uroporphyrinogen III|M00925 and M00122|B12|B12_00|
|Cobalamin (B12) - anaerobic|uroporphyrinogen III|M00924 and M00122|B12|B12_01|

## Repository Contents
- `Amino_Acids.txt` and `Vitamins.txt`: two tab-delimited text files describing our custom module definitions, with notes on how we created them (e.g., based on which KEGG Modules or KEGG Pathway Maps). These are `.txt` versions of Supplementary Tables that will be provided with the paper.
- `gen_module_files.py`: a script that can generate properly-formatted module files for [`anvi-setup-user-modules`](https://anvio.org/help/8/programs/anvi-setup-user-modules/) from the two aforementioned tab-delimited text files.
- the `USER_MODULES/` directory: contains the custom module information in [a data directory formatted for anvi'o](https://anvio.org/help/8/artifacts/user-modules-data/)

## How to estimate metabolism using these custom modules

The anvi'o program `anvi-estimate-metabolism` can work directly with the custom modules stored in the `USER_MODULES/`. We recommend reading the [program documentation](https://anvio.org/help/8/programs/anvi-estimate-metabolism/) to find the parameters that work for your use-case, but here is one example command that provides an [external genomes file](https://anvio.org/help/8/artifacts/external-genomes/) of annotated contigs databases to the program and asks it to provide matrix-formatted output for only these 30 custom modules:

```
anvi-estimate-metabolism -e external-genomes.txt \
   -u USER_MODULES/  \
   --only-user-modules \
   --matrix-format \
   -O custom_biosynthesis
```

Note that your genomes (or metagenomes) should be annotated with KEGG KOfams in order for this to work, since the custom modules are defined using Kegg Ortholog (KO) accession numbers.

## How to generate a modules database from the custom module definitions

If you want to change something in the module definitions and you update the `Amino_Acids.txt` or `Vitamins.txt` files, you should then re-generate the module files in the `USER_MODULES` directory.

### Step 1: find (or obtain) KEGG data on your computer

Even though these are custom modules, we are going to need access to KEGG data in order to look up definitions of KEGG KOfam functions for each of the KOs in our module definitions.

If you want to match the KEGG data used in our paper, you should use the anvi'o KEGG snapshot with hash value `a2b5bde358bb` (downloaded from KEGG in September 2023). Here is how you can download that particular version:

```
anvi-setup-kegg-data --kegg-snapshot v2023-09-22 --kegg-data-dir KEGG_a2b5bde358bb/
```

In case you already have a different version of KEGG data elsewhere on your computer (that you want to use), anytime you see the path `KEGG_a2b5bde358bb/` below, you could replace it with the path to the [KEGG data directory](https://anvio.org/help/8/artifacts/kegg-data/) on your own computer.

### Step 2: Run `gen_module_files.py`

We use the script `gen_module_files.py` to create a [user-defined module file](https://anvio.org/help/main/programs/anvi-setup-user-modules/#how-do-i-format-the-module-files), following KEGG's formatting rules, for each custom module. Here is how to run it:

```
python gen_module_files.py Amino_Acids.txt KEGG_a2b5bde358bb/ USER_MODULES
python gen_module_files.py Vitamins.txt KEGG_a2b5bde358bb/ USER_MODULES
```

The first parameter is either of the tab-delimited module data sheets, the second parameter is the path to the KEGG data directory (ideally, matching the version used to annotate your contigs databases), and the third parameter is the desired name of the output directory. If the script finishes successfully, you should see output on the screen looking like this:

```
Printed ALA_00 to output file path: USER_MODULES/modules/ALA_00
Printed ASP_00 to output file path: USER_MODULES/modules/ASP_00
(...)
```

### Step 3: run `anvi-setup-user-modules`

Then you can turn those plain text files into a database for anvi'o to read from:

```
anvi-setup-user-modules -u USER_MODULES/ --kegg-data-dir KEGG_a2b5bde358bb/
```

The KEGG data is needed here for sanity checking that there aren't any conflicting module names between the KEGG modules and the custom modules, in case you decide to work with both databases at the same time later.

